"""Render the native Wayfinder formula and update Concepta's public tap."""
import argparse
from pathlib import Path
import re
import shutil
import subprocess
import tempfile

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('artifacts', type=Path)
parser.add_argument('--output', type=Path, help='Render locally without publishing')
args = parser.parse_args()
root = Path(__file__).resolve().parents[2]
version = re.search(r'^version: (.+)$', (root / 'packages/wayfinder/pubspec.yaml').read_text(), re.M)[1]
if not re.fullmatch(r'\d+\.\d+\.\d+(?:-[A-Za-z0-9.-]+)?', version):
    parser.error('Invalid version')
formula = (root / 'tool/homebrew/wayfinder.rb.template').read_text().replace('{{VERSION}}', version)
for platform, key in [('macos-arm64', 'MACOS'), ('linux-x64', 'LINUX')]:
    digest = (args.artifacts / f'wayfinder-{platform}.tar.gz.sha256').read_text().split()[0]
    if not re.fullmatch('[0-9a-f]{64}', digest):
        parser.error('Invalid archive checksum')
    formula = formula.replace('{{' + key + '_SHA256}}', digest)
def render(destination):
    (destination / 'Formula').mkdir(parents=True, exist_ok=True)
    (destination / 'Formula/wayfinder.rb').write_text(formula)
    if not (destination / 'Formula/okfp.rb').exists():
        shutil.copy2(root / 'tool/homebrew/okfp.rb', destination / 'Formula/okfp.rb')
    readme = destination / 'README.md'
    text = readme.read_text() if readme.exists() else '# Concepta Homebrew Tap\n'
    marker = '\n## Wayfinder and Profile validation\n'
    if marker in text:
        text = text.split(marker)[0]
    text += marker + '''
```sh
brew install conceptadev/tap/wayfinder
```

Wayfinder installs a complete native runtime and model. Its `okfp` dependency
provides the Profile validation gate and may be installed separately with
`brew install conceptadev/tap/okfp`. The validator builds with a pinned temporary
Dart SDK; no SDK setup is required from the user. Wayfinder supports macOS Apple
Silicon and Linux x64. Upgrade with `brew upgrade wayfinder okfp`.

These formulas are generated by the Wayfinder source release workflow. See the
[public installation guide](https://github.com/conceptadev/wayfinder-dist/blob/main/docs/install.md).
'''
    readme.write_text(text)
if args.output:
    render(args.output)
else:
    with tempfile.TemporaryDirectory(prefix='wayfinder-tap-') as temporary:
        destination = Path(temporary) / 'tap'
        git = ['git', '-c', 'credential.helper=!gh auth git-credential']
        subprocess.run([*git, 'clone', '--depth', '1', 'https://github.com/conceptadev/homebrew-tap.git', str(destination)], check=True)
        render(destination)
        subprocess.run(['git', '-C', str(destination), 'add', 'Formula/wayfinder.rb', 'Formula/okfp.rb', 'README.md'], check=True)
        if subprocess.run(['git', '-C', str(destination), 'diff', '--cached', '--quiet']).returncode:
            subprocess.run(['git', '-C', str(destination), '-c', 'user.name=Wayfinder Release',
                '-c', 'user.email=wayfinder-release@users.noreply.github.com', 'commit', '-m', f'Release Wayfinder {version} and its validation gate'], check=True)
            subprocess.run([*git, '-C', str(destination), 'push', 'origin', 'HEAD'], check=True)
