// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;

import 'src/storage/embedding_entities.dart';
import 'src/storage/objectbox_entities.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 8868627367577742574),
    name: 'ChunkEntity',
    lastPropertyId: const obx_int.IdUid(8, 7905200579896436563),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 7306576966961631738),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5225304567287435765),
        name: 'chunkId',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(1, 4458246288912427447),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 9112981691790776457),
        name: 'sourcePath',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 8185922811376432678),
        name: 'lineStart',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 1745426832894857757),
        name: 'lineEnd',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 2418944110626747895),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1172374795224096583),
        name: 'type',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 7905200579896436563),
        name: 'metadataJson',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 5454060788371618184),
    name: 'EmbeddingEntity768',
    lastPropertyId: const obx_int.IdUid(7, 1947303555228418944),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1193394587907611662),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 9193266036610955617),
        name: 'embeddingKey',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(2, 5309712781584971678),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 8774359902648244740),
        name: 'chunkId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 8260255726227913698),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7295914250334259545),
        name: 'source',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(4, 1494647201565118131),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 8954943725731155925),
        name: 'modelName',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(5, 7369963232150480847),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5527448626657189885),
        name: 'vector',
        type: 28,
        flags: 8,
        indexId: const obx_int.IdUid(6, 8661905253805283419),
        hnswParams: obx_int.ModelHnswParams(dimensions: 768, distanceType: 2),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 1947303555228418944),
        name: 'chunkRelationId',
        type: 11,
        flags: 520,
        indexId: const obx_int.IdUid(7, 6260536262635163689),
        relationField: 'chunkRelation',
        relationTarget: 'ChunkEntity',
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
obx.Store openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) {
  return obx.Store(
    getObjectBoxModel(),
    directory: directory,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 5454060788371618184),
    lastIndexId: const obx_int.IdUid(7, 6260536262635163689),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ChunkEntity: obx_int.EntityDefinition<ChunkEntity>(
      model: _entities[0],
      toOneRelations: (ChunkEntity object) => [],
      toManyRelations: (ChunkEntity object) => {},
      getId: (ChunkEntity object) => object.id,
      setId: (ChunkEntity object, int id) {
        object.id = id;
      },
      objectToFB: (ChunkEntity object, fb.Builder fbb) {
        final chunkIdOffset = fbb.writeString(object.chunkId);
        final sourcePathOffset = fbb.writeString(object.sourcePath);
        final contentOffset = fbb.writeString(object.content);
        final typeOffset = fbb.writeString(object.type);
        final metadataJsonOffset = fbb.writeString(object.metadataJson);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, chunkIdOffset);
        fbb.addOffset(2, sourcePathOffset);
        fbb.addInt64(3, object.lineStart);
        fbb.addInt64(4, object.lineEnd);
        fbb.addOffset(5, contentOffset);
        fbb.addOffset(6, typeOffset);
        fbb.addOffset(7, metadataJsonOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final chunkIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final sourcePathParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final lineStartParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final lineEndParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 14, '');
        final typeParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 16, '');
        final metadataJsonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final object = ChunkEntity(
          id: idParam,
          chunkId: chunkIdParam,
          sourcePath: sourcePathParam,
          lineStart: lineStartParam,
          lineEnd: lineEndParam,
          content: contentParam,
          type: typeParam,
          metadataJson: metadataJsonParam,
        );

        return object;
      },
    ),
    EmbeddingEntity768: obx_int.EntityDefinition<EmbeddingEntity768>(
      model: _entities[1],
      toOneRelations: (EmbeddingEntity768 object) => [object.chunkRelation],
      toManyRelations: (EmbeddingEntity768 object) => {},
      getId: (EmbeddingEntity768 object) => object.id,
      setId: (EmbeddingEntity768 object, int id) {
        object.id = id;
      },
      objectToFB: (EmbeddingEntity768 object, fb.Builder fbb) {
        final embeddingKeyOffset = fbb.writeString(object.embeddingKey);
        final chunkIdOffset = fbb.writeString(object.chunkId);
        final sourceOffset = fbb.writeString(object.source);
        final modelNameOffset = fbb.writeString(object.modelName);
        final vectorOffset = fbb.writeListFloat32(object.vector);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, embeddingKeyOffset);
        fbb.addOffset(2, chunkIdOffset);
        fbb.addOffset(3, sourceOffset);
        fbb.addOffset(4, modelNameOffset);
        fbb.addOffset(5, vectorOffset);
        fbb.addInt64(6, object.chunkRelation.targetId);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final embeddingKeyParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final chunkIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final sourceParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final modelNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final vectorParam = const obx_int.Float32ListReader().vTableGet(
          buffer,
          rootOffset,
          14,
          Float32List(0),
        );
        final object = EmbeddingEntity768(
          id: idParam,
          embeddingKey: embeddingKeyParam,
          chunkId: chunkIdParam,
          source: sourceParam,
          modelName: modelNameParam,
          vector: vectorParam,
        );
        object.chunkRelation.targetId = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        object.chunkRelation.attach(store);
        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ChunkEntity] entity fields to define ObjectBox queries.
class ChunkEntity_ {
  /// See [ChunkEntity.id].
  static final id = obx.QueryIntegerProperty<ChunkEntity>(
    _entities[0].properties[0],
  );

  /// See [ChunkEntity.chunkId].
  static final chunkId = obx.QueryStringProperty<ChunkEntity>(
    _entities[0].properties[1],
  );

  /// See [ChunkEntity.sourcePath].
  static final sourcePath = obx.QueryStringProperty<ChunkEntity>(
    _entities[0].properties[2],
  );

  /// See [ChunkEntity.lineStart].
  static final lineStart = obx.QueryIntegerProperty<ChunkEntity>(
    _entities[0].properties[3],
  );

  /// See [ChunkEntity.lineEnd].
  static final lineEnd = obx.QueryIntegerProperty<ChunkEntity>(
    _entities[0].properties[4],
  );

  /// See [ChunkEntity.content].
  static final content = obx.QueryStringProperty<ChunkEntity>(
    _entities[0].properties[5],
  );

  /// See [ChunkEntity.type].
  static final type = obx.QueryStringProperty<ChunkEntity>(
    _entities[0].properties[6],
  );

  /// See [ChunkEntity.metadataJson].
  static final metadataJson = obx.QueryStringProperty<ChunkEntity>(
    _entities[0].properties[7],
  );
}

/// [EmbeddingEntity768] entity fields to define ObjectBox queries.
class EmbeddingEntity768_ {
  /// See [EmbeddingEntity768.id].
  static final id = obx.QueryIntegerProperty<EmbeddingEntity768>(
    _entities[1].properties[0],
  );

  /// See [EmbeddingEntity768.embeddingKey].
  static final embeddingKey = obx.QueryStringProperty<EmbeddingEntity768>(
    _entities[1].properties[1],
  );

  /// See [EmbeddingEntity768.chunkId].
  static final chunkId = obx.QueryStringProperty<EmbeddingEntity768>(
    _entities[1].properties[2],
  );

  /// See [EmbeddingEntity768.source].
  static final source = obx.QueryStringProperty<EmbeddingEntity768>(
    _entities[1].properties[3],
  );

  /// See [EmbeddingEntity768.modelName].
  static final modelName = obx.QueryStringProperty<EmbeddingEntity768>(
    _entities[1].properties[4],
  );

  /// See [EmbeddingEntity768.vector].
  static final vector = obx.QueryHnswProperty<EmbeddingEntity768>(
    _entities[1].properties[5],
  );

  /// See [EmbeddingEntity768.chunkRelation].
  static final chunkRelation =
      obx.QueryRelationToOne<EmbeddingEntity768, ChunkEntity>(
        _entities[1].properties[6],
      );
}
