import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

/// Embeds the installed Profile files under `profile/` as Dart constants so a
/// release validates offline, from the binary alone. Run from the workspace
/// root; `--check` exits non-zero when the generated file is stale.
Future<void> main(List<String> arguments) async {
  final check = arguments.contains('--check');
  if (arguments.any((argument) => argument != '--check')) {
    stderr.writeln(
      'Usage: dart run tool/generate_installed_profiles.dart [--check]',
    );
    exitCode = 64;
    return;
  }
  final workspace = Directory.current.path;
  final output = File(
    p.join(
      workspace,
      'packages',
      'wayfinder',
      'lib',
      'src',
      'generated',
      'installed_profiles.g.dart',
    ),
  );
  final generated = await _format(
    _render([
      await _EmbeddedSet.read(
        workspace,
        constant: 'installedProfileManifests',
        doc: 'Installed Profile manifests, raw JSON keyed by (id, release).',
        current: 'wayfinder-profile.json',
        snapshotPrefix: 'wayfinder-profile-',
      ),
      await _EmbeddedSet.read(
        workspace,
        constant: 'installedRuleCatalogs',
        doc:
            'Installed Profile rule catalogs, raw JSON keyed by (id, release).',
        current: 'wayfinder-rules.json',
        snapshotPrefix: 'wayfinder-rules-',
      ),
    ]),
  );
  final existing = await output.exists() ? await output.readAsString() : null;
  if (check) {
    if (existing == generated) return;
    stderr.writeln(
      '${p.relative(output.path, from: workspace)} is stale; run '
      'dart run tool/generate_installed_profiles.dart.',
    );
    exitCode = 1;
    return;
  }
  if (existing != generated) {
    await output.parent.create(recursive: true);
    await output.writeAsString(generated);
  }
  stdout.writeln('Wrote ${p.relative(output.path, from: workspace)}');
}

/// One generated constant: the current file in `profile/` plus every
/// immutable snapshot of it under `profile/versions/`.
final class _EmbeddedSet {
  const _EmbeddedSet(this.constant, this.doc, this.entries);

  static Future<_EmbeddedSet> read(
    String workspace, {
    required String constant,
    required String doc,
    required String current,
    required String snapshotPrefix,
  }) async {
    final profile = p.join(workspace, 'profile');
    final files = <File>[
      File(p.join(profile, current)),
      ...Directory(p.join(profile, 'versions'))
          .listSync()
          .whereType<File>()
          .where((file) => p.basename(file.path).startsWith(snapshotPrefix)),
    ];
    final entries = <(String, String), String>{};
    for (final file in files) {
      final text = await file.readAsString();
      if (text.contains("'''")) {
        throw FormatException(
          "${file.path} contains ''' and cannot be embedded",
        );
      }
      final json = jsonDecode(text) as Map<String, Object?>;
      final key = _key(json, file.path);
      if (entries.containsKey(key)) {
        throw FormatException('${file.path} repeats the release $key');
      }
      entries[key] = text;
    }
    final sorted = entries.entries.toList()
      ..sort((left, right) => '${left.key}'.compareTo('${right.key}'));
    return _EmbeddedSet(constant, doc, sorted);
  }

  /// A manifest keys itself by `id` and `release`; a rule catalog nests
  /// them under `profile`.
  static (String, String) _key(Map<String, Object?> json, String path) {
    final profile = json['profile'];
    final source = profile is Map<String, Object?> ? profile : json;
    final id = source['id'];
    final release = source['release'];
    if (id is! String || release is! String) {
      throw FormatException('$path lacks a string id and release');
    }
    return (id, release);
  }

  final String constant;
  final String doc;
  final List<MapEntry<(String, String), String>> entries;
}

String _render(List<_EmbeddedSet> sets) {
  final buffer = StringBuffer(
    '// GENERATED by tool/generate_installed_profiles.dart from profile/. '
    'Do not edit.\n',
  );
  for (final set in sets) {
    buffer
      ..writeln()
      ..writeln('/// ${set.doc}')
      ..writeln('const Map<(String, String), String> ${set.constant} = {');
    for (final MapEntry(key: (id, release), value: text) in set.entries) {
      buffer
        ..writeln("  ('$id', '$release'): r'''")
        ..write(text)
        ..writeln("''',");
    }
    buffer.writeln('};');
  }
  return buffer.toString();
}

Future<String> _format(String source) async {
  final directory = await Directory.systemTemp.createTemp(
    'installed-profiles-',
  );
  try {
    final file = File(p.join(directory.path, 'installed_profiles.g.dart'));
    await file.writeAsString(source);
    final result = await Process.run(Platform.resolvedExecutable, [
      'format',
      file.path,
    ]);
    if (result.exitCode != 0) {
      throw ProcessException(
        'dart',
        ['format'],
        '${result.stderr}',
        result.exitCode,
      );
    }
    return await file.readAsString();
  } finally {
    await directory.delete(recursive: true);
  }
}
