import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

Future<void> main(List<String> arguments) async {
  final check = arguments.contains('--check');
  if (arguments.any((argument) => argument != '--check')) {
    stderr.writeln(
      'Usage: dart run tool/generate_installed_profiles.dart [--check]',
    );
    exitCode = 64;
    return;
  }
  final workspace = Directory.current.path;
  final output = File(
    p.join(
      workspace,
      'packages',
      'wayfinder',
      'lib',
      'src',
      'generated',
      'installed_profiles.g.dart',
    ),
  );
  final generated = await _format(
    _render(
      [
        await _EmbeddedSet.read(
          workspace,
          constant: 'installedProfileManifests',
          doc: 'Installed Profile manifests, raw JSON keyed by (id, release).',
          file: 'wayfinder-profile.json',
        ),
        await _EmbeddedSet.read(
          workspace,
          constant: 'installedRuleCatalogs',
          doc:
              'Installed Profile rule catalogs, raw JSON keyed by (id, release).',
          file: 'wayfinder-rules.json',
        ),
      ],
      [
        await _EmbeddedFile.read(
          workspace,
          constant: 'wayfinderConfigurationSchema',
          doc: 'The published `wayfinder.json` schema, raw JSON.',
          path: 'docs/schemas/wayfinder.schema.json',
        ),
        await _EmbeddedFile.read(
          workspace,
          constant: 'wayfinderProfileManifestSchema',
          doc: 'The published Profile manifest schema, raw JSON.',
          path: 'docs/schemas/wayfinder-profile.schema.json',
        ),
        await _EmbeddedFile.read(
          workspace,
          constant: 'wayfinderRulesSchema',
          doc: 'The published Profile rule catalog schema, raw JSON.',
          path: 'docs/schemas/wayfinder-rules.schema.json',
        ),
      ],
    ),
  );
  final existing = await output.exists() ? await output.readAsString() : null;
  if (check) {
    if (existing == generated) return;
    stderr.writeln(
      '${p.relative(output.path, from: workspace)} is stale; run '
      'dart run tool/generate_installed_profiles.dart.',
    );
    exitCode = 1;
    return;
  }
  if (existing != generated) {
    await output.parent.create(recursive: true);
    await output.writeAsString(generated);
  }
  stdout.writeln('Wrote ${p.relative(output.path, from: workspace)}');
}

final class _EmbeddedSet {
  const _EmbeddedSet(this.constant, this.doc, this.entries);

  /// Only the live release under `profile/`; superseded snapshots in
  /// `profile/versions/` are an archive the engine no longer assesses.
  static Future<_EmbeddedSet> read(
    String workspace, {
    required String constant,
    required String doc,
    required String file,
  }) async {
    final path = p.join(workspace, 'profile', file);
    final text = await _embeddable(File(path));
    final key = _key(jsonDecode(text) as Map<String, Object?>, path);
    return _EmbeddedSet(constant, doc, [MapEntry(key, text)]);
  }

  static (String, String) _key(Map<String, Object?> json, String path) {
    final profile = json['profile'];
    final source = profile is Map<String, Object?> ? profile : json;
    final id = source['id'];
    final release = source['release'];
    if (id is! String || release is! String) {
      throw FormatException('$path lacks a string id and release');
    }
    return (id, release);
  }

  final String constant;
  final String doc;
  final List<MapEntry<(String, String), String>> entries;
}

final class _EmbeddedFile {
  const _EmbeddedFile(this.constant, this.doc, this.text);

  static Future<_EmbeddedFile> read(
    String workspace, {
    required String constant,
    required String doc,
    required String path,
  }) async => _EmbeddedFile(
    constant,
    doc,
    await _embeddable(File(p.join(workspace, path))),
  );

  final String constant;
  final String doc;
  final String text;
}

Future<String> _embeddable(File file) async {
  final text = await file.readAsString();
  if (text.contains("'''")) {
    throw FormatException("${file.path} contains ''' and cannot be embedded");
  }
  return text;
}

String _render(List<_EmbeddedSet> sets, List<_EmbeddedFile> files) {
  final buffer = StringBuffer(
    '// GENERATED by tool/generate_installed_profiles.dart from profile/. '
    'Do not edit.\n',
  );
  for (final set in sets) {
    buffer
      ..writeln()
      ..writeln('/// ${set.doc}')
      ..writeln('const Map<(String, String), String> ${set.constant} = {');
    for (final MapEntry(key: (id, release), value: text) in set.entries) {
      buffer
        ..writeln("  ('$id', '$release'): r'''")
        ..write(text)
        ..writeln("''',");
    }
    buffer.writeln('};');
  }
  for (final file in files) {
    buffer
      ..writeln()
      ..writeln('/// ${file.doc}')
      ..writeln("const String ${file.constant} = r'''")
      ..write(file.text)
      ..writeln("''';");
  }
  return buffer.toString();
}

Future<String> _format(String source) async {
  final directory = await Directory.systemTemp.createTemp(
    'installed-profiles-',
  );
  try {
    final file = File(p.join(directory.path, 'installed_profiles.g.dart'));
    await file.writeAsString(source);
    final result = await Process.run(Platform.resolvedExecutable, [
      'format',
      file.path,
    ]);
    if (result.exitCode != 0) {
      throw ProcessException(
        'dart',
        ['format'],
        '${result.stderr}',
        result.exitCode,
      );
    }
    return await file.readAsString();
  } finally {
    await directory.delete(recursive: true);
  }
}
