import 'dart:io';

import 'package:path/path.dart' as p;

/// Embeds what the engine must know at runtime but owns elsewhere: the two
/// published schemas it validates input against, and the version of the
/// okf package its index generator comes from. okf exports no version
/// constant, so the engine's pubspec pins okf to one exact version and that
/// pin is the checked-in source of truth. No Profile is embedded; every
/// Profile is fetched like any other.
Future<void> main(List<String> arguments) async {
  final check = arguments.contains('--check');
  if (arguments.any((argument) => argument != '--check')) {
    stderr.writeln(
      'Usage: dart run tool/generate_published_schemas.dart [--check]',
    );
    exitCode = 64;
    return;
  }
  final workspace = Directory.current.path;
  final output = File(
    p.join(
      workspace,
      'packages',
      'wayfinder',
      'lib',
      'src',
      'generated',
      'published_schemas.g.dart',
    ),
  );
  final generated = await _format(
    _render([
      _Constant(
        'wayfinderConfigurationSchema',
        'The published `wayfinder.json` schema, raw JSON.',
        await _embeddable(
          File(p.join(workspace, 'docs', 'schemas', 'wayfinder.schema.json')),
        ),
      ),
      _Constant(
        'wayfinderProfileSchema',
        'The published Profile package schema, raw JSON.',
        await _embeddable(
          File(
            p.join(
              workspace,
              'docs',
              'schemas',
              'wayfinder-profile.schema.json',
            ),
          ),
        ),
      ),
      _Constant(
        'okfPackageVersion',
        'The okf package this engine generates indexes with.',
        await _pinnedVersion(
          File(p.join(workspace, 'packages', 'wayfinder', 'pubspec.yaml')),
          'okf',
        ),
        raw: false,
      ),
    ]),
  );
  final existing = await output.exists() ? await output.readAsString() : null;
  if (check) {
    if (existing == generated) return;
    stderr.writeln(
      '${p.relative(output.path, from: workspace)} is stale; run '
      'dart run tool/generate_published_schemas.dart.',
    );
    exitCode = 1;
    return;
  }
  if (existing != generated) {
    await output.parent.create(recursive: true);
    await output.writeAsString(generated);
  }
  stdout.writeln('Wrote ${p.relative(output.path, from: workspace)}');
}

final class _Constant {
  const _Constant(this.name, this.doc, this.text, {this.raw = true});

  final String name;
  final String doc;
  final String text;

  /// Multi-line JSON is embedded as a raw triple-quoted string; a short
  /// value as an ordinary literal.
  final bool raw;
}

Future<String> _embeddable(File file) async {
  final text = await file.readAsString();
  if (text.contains("'''")) {
    throw FormatException("${file.path} contains ''' and cannot be embedded");
  }
  return text;
}

/// The exact version [pubspec] pins [package] to. A range would let the
/// embedded version drift from the resolved one, so only `name: x.y.z`
/// is accepted.
Future<String> _pinnedVersion(File pubspec, String package) async {
  final match = RegExp(
    '^  $package: ([0-9]+\\.[0-9]+\\.[0-9]+(?:[+-][0-9A-Za-z.]+)?)\$',
    multiLine: true,
  ).firstMatch(await pubspec.readAsString());
  if (match == null) {
    throw FormatException('${pubspec.path} must pin $package to one version');
  }
  return match[1]!;
}

String _render(List<_Constant> constants) {
  final buffer = StringBuffer(
    '// GENERATED by tool/generate_published_schemas.dart. Do not edit.\n',
  );
  for (final constant in constants) {
    buffer
      ..writeln()
      ..writeln('/// ${constant.doc}');
    if (constant.raw) {
      buffer
        ..writeln("const String ${constant.name} = r'''")
        ..write(constant.text)
        ..writeln("''';");
    } else {
      buffer.writeln("const String ${constant.name} = '${constant.text}';");
    }
  }
  return buffer.toString();
}

Future<String> _format(String source) async {
  final directory = await Directory.systemTemp.createTemp('published-schemas-');
  try {
    final file = File(p.join(directory.path, 'published_schemas.g.dart'));
    await file.writeAsString(source);
    final result = await Process.run(Platform.resolvedExecutable, [
      'format',
      file.path,
    ]);
    if (result.exitCode != 0) {
      throw ProcessException(
        'dart',
        ['format'],
        '${result.stderr}',
        result.exitCode,
      );
    }
    return await file.readAsString();
  } finally {
    await directory.delete(recursive: true);
  }
}
